# .Site config
baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "Test Hugo Site"
description = "Sample description"
pluralizelisttitles = false
preserveTaxonomyNames = true
paginate = 5

[author]
  name = "Hanna Liebl"

[taxonomies]
  tag = "tags"
  category = "categories"
  featured = "featured"
